version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: 'kensobi-spc-panel'
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/kensobi-spc-panel
#      - spc_panel_storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_DEFAULT_APP_MODE=development
#volumes:
#  spc_panel_storage:

